-- CREATE DATABASE 'DataWareHouse'

USE master;

CREATE DATABASE DataWarehouse;

USE DataWareHouse;

--GO - SEPARATES BATCHES WHEN WORKING WITH MULTIPLE SQL STATEMENTS
CREATE SCHEMA bronze;
GO
CREATE SCHEMA silver;
GO
CREATE SCHEMA gold;
GO
